#!/bin/sh
#PBS -N R0040235
#PBS -j oe
#PBS -l walltime=16:00:00
#PBS -l nodes=1:ppn=6
#PBS -l mem=120GB
#PBS -q lm
#PBS -m ae
#PBS -M eb.mtl@pm.me
#PBS -A vdu-032-ad
#
module load itgenome/pacbiotools/0.0.0

# Set environment variables (make sure paths are correct)
SAMPLE="R0040235"
BASEDIR="/lb/project/GRID/NOBACKUP/eba/"
REF_FILE="${BASEDIR}/RS_PacBio_WGS_202X/ref/hg38.fasta"
INPUT_DIR="${BASEDIR}/RS_PacBio_WGS_202X/final/hg38/SV"
RSRC_FILE="${BASEDIR}/RS_PacBio_WGS_202X/resources/GRCh38/ensembl.GRCh38.101.reformatted.gff3.gz"
CTRL_FILE="${BASEDIR}/RS_PacBio_WGS_202X/resources/GRCh38/sv_pop_vcfs/hprc.GRCh38.pbsv.vcf.gz"

cd ${INPUT_DIR}/

tmpfile=$(mktemp)
cat ${RSRC_FILE} > $tmpfile
zcat ${SAMPLE}.SV.vcf.gz | \
svpack filter --pass-only --min-svlen 50 - | \
svpack match -v - ${CTRL_FILE} | \
svpack consequence --require-csq - $tmpfile > ${SAMPLE}.GiaB.SV.tsv
rm $tmpfile
grep  "sv:cds" ${SAMPLE}.GiaB.SV.tsv | cut -f1-3,8 > ${SAMPLE}.GiaB.SV.coding.exon.impact.tsv

CTRL_FILE="${BASEDIR}/RS_PacBio_WGS_202X/resources/GRCh38/sv_pop_vcfs/EEE_SV-Pop_1.ALL.sites.20181204.vcf.gz"
tmpfile=$(mktemp)
cat ${RSRC_FILE} > $tmpfile
zcat ${SAMPLE}.SV.vcf.gz | \
svpack filter --pass-only --min-svlen 50 - | \
svpack match -v - ${CTRL_FILE} | \
svpack consequence --require-csq - $tmpfile > ${SAMPLE}.PacBioPop.SV.tsv
rm $tmpfile
grep  "sv:cds" ${SAMPLE}.PacBioPop.SV.tsv | cut -f1-3,8 > ${SAMPLE}.PacBioPop.SV.coding.exon.impact.tsv


CTRL_FILE="${BASEDIR}/RS_PacBio_WGS_202X/resources/GRCh38/sv_pop_vcfs/nstd166.GRCh38.variant_call.vcf.gz"
tmpfile=$(mktemp)
cat ${RSRC_FILE} > $tmpfile
zcat ${SAMPLE}.SV.vcf.gz | \
svpack filter --pass-only --min-svlen 50 - | \
svpack match -v - ${CTRL_FILE} | \
svpack consequence --require-csq - $tmpfile > ${SAMPLE}.gnomAD.SV.tsv
rm $tmpfile
grep  "sv:cds" ${SAMPLE}.gnomAD.SV.tsv | cut -f1-3,8 > ${SAMPLE}.gnomAD.SV.coding.exon.impact.tsv


CTRL_FILE="${BASEDIR}/RS_PacBio_WGS_202X/resources/GRCh38/sv_pop_vcfs/ont_sv_high_confidence_SVs.sorted.vcf.gz"
tmpfile=$(mktemp)
cat ${RSRC_FILE} > $tmpfile
zcat ${SAMPLE}.SV.vcf.gz | \
svpack filter --pass-only --min-svlen 50 - | \
svpack match -v - ${CTRL_FILE} | \
svpack consequence --require-csq - $tmpfile > ${SAMPLE}.Icelanders.SV.tsv
rm $tmpfile
grep  "sv:cds" ${SAMPLE}.Icelanders.SV.tsv | cut -f1-3,8 > ${SAMPLE}.Icelanders.SV.coding.exon.impact.tsv

module unload itgenome/pacbiotools/0.0.0
